name: update-aws-lambda-functions

on:
  push:
    branches:
      - main
    paths:
      - "_server/**"

jobs:
  deploy:
    name: Update Lambda functions
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip and update functions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          functions=$(ls _server/functions)
          for f in $functions
          do
            cd $GITHUB_WORKSPACE/_server/functions/$f
            zip $GITHUB_WORKSPACE/$f.zip lambda_function.py
            cd $GITHUB_WORKSPACE/_server
            zip -ur $GITHUB_WORKSPACE/$f.zip common
            aws lambda update-function-code --function-name $f --zip-file fileb://$GITHUB_WORKSPACE/$f.zip
          done
